scene.setBackgroundColor(0)
let mySprite = sprites.create(assets.image`flamingo`, SpriteKind.Player)
let mySprite2 = sprites.create(assets.image`fish_orange`, SpriteKind.Player)
mySprite.setPosition(80, 55)
mySprite2.setPosition(92, 71)
